name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    # 1. Java 17 설치
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    # 2. Spring 설정 파일 생성
    - name: make properties
      uses: actions/checkout@v3
    - run: mkdir -p ./src/main/resources
    - run: touch ./src/main/resources/application.yml
    - run: touch ./src/main/resources/application-dev.yml
    - run: echo "${{ secrets.APPLICATION }}" > ./src/main/resources/application.yml
    - run: echo "${{ secrets.APPLICATION_DEV }}" > ./src/main/resources/application-dev.yml
        
    # 3. SpringBoot 애플리케이션 빌드
    - name: Build with Gradle
      uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
      with:
        arguments: clean bootJar

    # 4. Docker 이미지 빌드
    - name: docker image build
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/you-and-i-backend .

    # 5. Docker Hub 로그인
    - name: docker login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    # 6. Docker Hub 이미지 push
    - name: docker Hub push
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/you-and-i-backend

  # docker image를 ec2에서 pull 받아서 실행
  run-docker-image-on-ec2:
    # build-docker-image (위) 과정이 완료 되어야 실행
    needs: build-docker-image
    runs-on: ubuntu-latest
    steps:
      - name: EC2 connect
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          password: ${{ secrets.EC2_PASSWORD }}
          port: ${{ secrets.EC2_SSH_PORT }}
          script: |
            docker ps -a
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/you-and-i-backend
            docker stop you-and-i-backend || true
            docker rm you-and-i-backend || true
            docker run -d -p 8080:8080 --name you-and-i-backend ${{ secrets.DOCKERHUB_USERNAME }}/you-and-i-backend
            sudo docker system prune -f